#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE USER auth_user WITH PASSWORD '$AUTH_DB_PASSWORD';
    CREATE USER game_user WITH PASSWORD '$GAME_DB_PASSWORD';
    CREATE USER ai_user   WITH PASSWORD '$AI_DB_PASSWORD';


    CREATE DATABASE db_auth;
    CREATE DATABASE db_game;
    CREATE DATABASE db_ai;

    GRANT ALL PRIVILEGES ON DATABASE db_auth TO auth_user;
    GRANT ALL PRIVILEGES ON DATABASE db_game TO game_user;
    GRANT ALL PRIVILEGES ON DATABASE db_ai   TO ai_user;
EOSQL