networks:
  jdr-network:
    driver: bridge

volumes:
  pgdata:
  vault-data:

services:

  gateway:
    build:
      context: .
      dockerfile: gateway/containerfile
    ports:
      - "2026:443"
    volumes:
      - ./gateway/certs:/etc/nginx/certs:Z
    networks:
      - jdr-network
    depends_on:
      - auth
      - game

  vault:
    image: docker.io/hashicorp/vault:1.17
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/data:Z
      - ./vault/config:/vault/config:Z
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
    entrypoint: vault server -config=/vault/config/vault.hcl
    networks:
      - jdr-network


  auth:
    build:
      context: ./services/auth
      dockerfile: containerfile
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_ROLE_ID: ${AUTH_VAULT_ROLE_ID}
      VAULT_SECRET_ID_FILE: /run/secrets/auth_vault_secret_id
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: db_auth
      VAULT_DB_ROLE: auth-db-role
      ACCESS_TOKEN_TTL_MINUTES: "15"
      REFRESH_TOKEN_TTL_DAYS: "7"
    secrets:
      - auth_vault_secret_id
    networks:
      - jdr-network
    depends_on:
      - postgres
      - vault

  game:
    build:
      context: ./services/game
      dockerfile: containerfile
    environment:
      DATABASE_URL: postgres://game_user:${GAME_DB_PASSWORD}@postgres:5432/db_game
      IA_SERVICE_URL: http://ia:8000
      # À revoir avec game pour récupération de la clé publique JWT
    networks:
      - jdr-network
    depends_on:
      - postgres

  ia:
    build:
      context: ./services/ia
      dockerfile: containerfile
    env_file:
      - ./.env
    environment:
      - DATABASE_URL
      - AI_DATABASE_URL
      - GROQ_API_KEY
      - LANGCHAIN_TRACING_V2
      - LANGCHAIN_API_KEY
      - LANGCHAIN_PROJECT
    networks:
      - jdr-network
    depends_on:
      - postgres

  postgres:
    image: docker.io/pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      GAME_DB_PASSWORD: ${GAME_DB_PASSWORD}
      AI_DB_PASSWORD: ${AI_DB_PASSWORD}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
      - ./database/init:/docker-entrypoint-initdb.d:Z
    networks:
      - jdr-network

secrets:
  auth_vault_secret_id:
    file: ./services/auth/secrets/vault_secret_id.txt