    FROM docker.io/node:20-alpine AS frontend-build

    RUN apk add --no-cache libc6-compat
    
    WORKDIR /app
    
    COPY frontend/package*.json ./
    RUN npm ci

    COPY frontend/ ./
    
    RUN ./node_modules/.bin/vite build
    
    FROM docker.io/nginx:1.27-alpine
    COPY gateway/nginx.conf /etc/nginx/nginx.conf
    COPY --from=frontend-build /app/dist /usr/share/nginx/html
    
    EXPOSE 80
    EXPOSE 443
    
    CMD ["nginx", "-g", "daemon off;"]