FROM docker.io/node:20-alpine AS frontend-build
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

FROM docker.io/nginx:1.27-alpine
COPY gateway/nginx.conf /etc/nginx/nginx.conf
COPY --from=frontend-build /dist /usr/share/nginx/html